DROP TABLE IF EXISTS course_enrollments CASCADE;
DROP TABLE IF EXISTS students_col_pk CASCADE;
DROP TABLE IF EXISTS students_table_pk CASCADE;
DROP TABLE IF EXISTS students_named_pk CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
