CREATE TABLE orders (
	order_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_name VARCHAR(100),
	order_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE customers (
	customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_name VARCHAR(100),
	email VARCHAR(150)
);

INSERT INTO customers (customer_id, customer_name, email) 
VALUES (1000, 'VIP Customer', 'vip@example.com');
